### ISSUE TITLE
LCU api依然可用，通信方式变化

### ISSUE THREAD

**Issue by duzhor** [Java-S12138/frank#116]
从`LeagueClientUx.exe`进程中获取`--riotclient-app-port`和`--remoting-auth-token`参数，使用websocket建立连接。不知道作者是否知晓这一变化。

**Comment by Java-S12138** [comment]
frank现在任然可以正常使用，感谢提醒Sent from my iPhoneOn Aug 23, 2023, at 11:52, Duzhor ***@***.***> wrote:﻿
从LeagueClientUx.exe进程中获取--riotclient-app-port和--remoting-auth-token参数，使用websocket建立连接。不知道作者是否知晓这一变化。

**Comment by duzhor** [comment]
暂时不考虑剥离cube是吗


> frank现在任然可以正常使用，感谢提醒Sent from my iPhoneOn Aug 23, 2023, at 11:52, Duzhor ***@***.***> wrote:﻿ 从LeagueClientUx.exe进程中获取--riotclient-app-port和--remoting-auth-token参数，使用websocket建立连接。不知道作者是否知晓这一变化。 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by Java-S12138** [comment]
有脱离cube的查询战绩软件，record，lolfrank.cn 可以查看Sent from my iPhoneOn Aug 23, 2023, at 13:54, Duzhor ***@***.***> wrote:﻿
暂时不考虑剥离cube是吗

frank现在任然可以正常使用，感谢提醒Sent from my iPhoneOn Aug 23, 2023, at 11:52, Duzhor @.> wrote:﻿ 从LeagueClientUx.exe进程中获取--riotclient-app-port和--remoting-auth-token参数，使用websocket建立连接。不知道作者是否知晓这一变化。 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: @.>
